-- New bounded failure codes; no changes to existing profiles, jobs or results.
ALTER TABLE job_attempts DROP CONSTRAINT attempt_failure_code;
ALTER TABLE job_attempts ADD CONSTRAINT attempt_failure_code CHECK(failure_code IN
 ('LEASE_EXPIRED','STOP_UNCONFIRMED','ATTEMPTS_EXHAUSTED','VALIDATOR_FAILED','INPUT_REJECTED','REPORT_REJECTED','RUNNER_STOPPED',
 'INVOCATION_UNCERTAIN','CODEX_NOT_AVAILABLE','CODEX_UNSUPPORTED_VERSION','CODEX_LOGIN_REQUIRED','CODEX_AUTH_UNSUPPORTED',
 'CODEX_SAFE_PROFILE_UNVERIFIED','CODEX_QUOTA','CODEX_TIMEOUT','CODEX_INVALID_OUTPUT','CODEX_OUTPUT_LIMIT','CODEX_PROCESS_FAILED',
 'CODEX_MODEL_NOT_AVAILABLE','CODEX_MODEL_QUERY_FAILED','CODEX_MODEL_CAPABILITY_MISMATCH','CODEX_ISOLATION_UNVERIFIED'));
